src/Dynamo/Bundle/ColonizationBundle/Entity/Colonization.php
<?php
/**
 * Created by PhpStorm.
 * User: majoskorec
 * Date: 7.1.2017
 * Time: 12:18
 */

namespace Dynamo\Bundle\ColonizationBundle\Entity;

use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Dynamo\Bundle\PortalBundle\Entity\AddedByInterface;
use Dynamo\Bundle\PortalBundle\Entity\CreatedAtInterface;
use Dynamo\Bundle\PortalBundle\Entity\Traits\AddedByTrait;
use Dynamo\Bundle\PortalBundle\Entity\Traits\CreatedAtTrait;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Class Colonization
 * @package Dynamo\Bundle\ColonizationBundle\Entity
 * @ORM\Entity()
 * @ORM\Table(name="dynamo_colonization")
 */
class Colonization implements CreatedAtInterface, AddedByInterface
{
    use AddedByTrait;
    use CreatedAtTrait;

    /**
     * @var int
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id()
     * @ORM\GeneratedValue()
     */
    private $id;

    /**
     * @var string
     * @ORM\Column(name="place", type="string", length=255, nullable=true)
     */
    private $place;

    /**
     * @var string
     * @Assert\Regex("/^\-?\d+(\.\d+)?, \-?\d+(\.\d+)?$/")
     * @ORM\Column(name="map", type="string", length=255, nullable=true)
     */
    private $map;

    /**
     * @var DateTime
     * @ORM\Column(name="date_from", type="date", nullable=false)
     */
    private $dateFrom;

    /**
     * @var DateTime
     * @ORM\Column(name="date_to", type="date", nullable=false)
     */
    private $dateTo;

    /**
     * @var string
     * @ORM\Column(name="note", type="text")
     */
    private $note;

    /**
     * @var ArrayCollection
     * @ORM\ManyToMany(targetEntity="Dynamo\Bundle\ResourceBundle\Entity\Resource", cascade={"all"})
     * @ORM\JoinTable(
     *  name="dynamo_colonization_resource",
     *  joinColumns={
     *      @ORM\JoinColumn(name="colonization_id", referencedColumnName="id", onDelete="CASCADE")
     *  },
     *  inverseJoinColumns={
     *      @ORM\JoinColumn(name="resource_id", referencedColumnName="id", onDelete="CASCADE")
     *  }
     * )
     */
    private $photos;

    /**
     * @var ArrayCollection
     * @ORM\ManyToMany(targetEntity="Dynamo\Bundle\UserBundle\Entity\User")
     * @ORM\JoinTable(
     *  name="dynamo_colonization_user",
     *  joinColumns={
     *      @ORM\JoinColumn(name="colonization_id", referencedColumnName="id")
     *  },
     *  inverseJoinColumns={
     *      @ORM\JoinColumn(name="user_id", referencedColumnName="id")
     *  }
     * )
     */
    private $colonizers;

    /**
     * @return bool
     */
    public function isCorrectMap()
    {
        return (bool) preg_match('/^\-?\d+(\.\d+)?, \-?\d+(\.\d+)?$/', $this->map);
    }

    /**
     * @return mixed
     */
    public function getMapLat()
    {
        try {
            list($lat, $lng) = preg_split("/, /", $this->map);
        } catch (\Exception $e) {
            return false;
        }
        return $lat;
    }

    /**
     * @return mixed
     */
    public function getMapLng()
    {
        try {
            list($lat, $lng) = preg_split("/, /", $this->map);
        } catch (\Exception $e) {
            return false;
        }
        return $lng;
    }

    /**
     * @return bool
     */
    public function isOneDay()
    {
        return $this->dateFrom == $this->dateTo;
    }

    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param int $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * @return string
     */
    public function getPlace()
    {
        return $this->place;
    }

    /**
     * @param string $place
     */
    public function setPlace($place)
    {
        $this->place = $place;
    }

    /**
     * @return string
     */
    public function getMap()
    {
        return $this->map;
    }

    /**
     * @param string $map
     */
    public function setMap($map)
    {
        $this->map = $map;
    }

    /**
     * @return DateTime
     */
    public function getDateFrom()
    {
        return $this->dateFrom;
    }

    /**
     * @param DateTime $dateFrom
     */
    public function setDateFrom(DateTime $dateFrom)
    {
        $this->dateFrom = $dateFrom;
    }

    /**
     * @return DateTime
     */
    public function getDateTo()
    {
        return $this->dateTo;
    }

    /**
     * @param DateTime $dateTo
     */
    public function setDateTo(DateTime $dateTo)
    {
        $this->dateTo = $dateTo;
    }

    /**
     * @return string
     */
    public function getNote()
    {
        return $this->note;
    }

    /**
     * @param string $note
     */
    public function setNote($note)
    {
        $this->note = $note;
    }

    /**
     * @return ArrayCollection
     */
    public function getPhotos()
    {
        return $this->photos;
    }

    /**
     * @param ArrayCollection $photos
     */
    public function setPhotos($photos)
    {
        if ($photos instanceof ArrayCollection) {
            $this->photos = $photos;
            return;
        }
        if (is_array($photos)) {
            $this->photos = new ArrayCollection($photos);
            return;
        }
        throw new \InvalidArgumentException(
            sprintf("%s expected array or ArrayCollection, got %s", __METHOD__, get_class($photos))
        );
    }

    /**
     * @return ArrayCollection
     */
    public function getColonizers()
    {
        return $this->colonizers;
    }

    /**
     * @param ArrayCollection $colonizers
     */
    public function setColonizers(ArrayCollection $colonizers)
    {
        $this->colonizers = $colonizers;
    }
}

src/Dynamo/Bundle/ColonizationBundle/Form/Type/ColonizationType.php
<?php
/**
 * Created by PhpStorm.
 * User: majoskorec
 * Date: 7.1.2017
 * Time: 13:13
 */

namespace Dynamo\Bundle\ColonizationBundle\Form\Type;

use Dynamo\Bundle\ColonizationBundle\Entity\Colonization;
use Dynamo\Bundle\PortalBundle\Form\Type\DatePickerType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Class ColonizationType
 * @package Dynamo\Bundle\ColonizationBundle\Form\Type
 */
class ColonizationType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('place', TextType::class, [
            'label' => 'colonization.place',
        ]);
        $builder->add('map', TextType::class, [
            'label' => 'colonization.map',
            'required' => false,
        ]);
        $builder->add('dateFrom', DatePickerType::class, [
            'label' => 'colonization.date_from',
            'widget' => 'single_text',
            'html5' => false,
            'attr' => ['class' => 'js-datepicker'],
        ]);
        $builder->add('dateTo', DatePickerType::class, [
            'label' => 'colonization.date_to',
            'widget' => 'single_text',
            'html5' => false,
            'attr' => ['class' => 'js-datepicker'],
        ]);
        $builder->add('note', TextareaType::class, [
            'label' => 'colonization.note',
        ]);
        $builder->add('photos', CollectionType::class, [
            'label' => 'colonization.photos',
            'entry_type' => ColonizationPhotoType::class,
            'entry_options' => array(
                'label' => false,
            ),
            'allow_add' => true,
            'allow_delete' => true,
            'prototype' => true,
            'attr' => ['class' => 'colonization-photos',],
        ]);
        $builder->add('colonizers', null, [
            'label' => 'colonization.colonizers',
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Colonization::class,
        ]);
    }
}

src/Dynamo/Bundle/ColonizationBundle/Controller/ColonizationController.php
<?php

namespace Dynamo\Bundle\ColonizationBundle\Controller;

use Dynamo\Bundle\ColonizationBundle\Entity\Colonization;
use Dynamo\Bundle\ColonizationBundle\Form\Type\ColonizationType;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Component\Form\Form;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Translation\TranslatorInterface;

/**
 * Class ColonizationController
 * @package Dynamo\Bundle\ColonizationBundle\Controller
 * @Route("/kolonizator")
 */
class ColonizationController extends Controller
{
    /**
     * @Route("/")
     * @Method("GET")
     * @return Response
     */
    public function indexAction()
    {
        $em = $this->getDoctrine()->getManager();

        $colonizations = $em->getRepository(Colonization::class)->findBy([], ["dateFrom" => "DESC"]);

        return $this->render('DynamoColonizationBundle:Colonization:index.html.twig', [
            'colonizations' => $colonizations,
        ]);
    }

    /**
     * @Route("/pridaj")
     * @Method({"GET", "POST"})
     * @param Request $request
     * @return Response
     * @Security("has_role('ROLE_USER')")
     */
    public function newAction(Request $request)
    {
        $colonization = new Colonization();
        $form = $this->createForm(ColonizationType::class, $colonization);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($colonization);
            $em->flush();
            $this->addFlash('success', $this->getTranslator()->trans("colonization.created"));
            return $this->redirectToRoute('dynamo_colonization_colonization_index');
        }

        return $this->render('DynamoColonizationBundle:Colonization:new.html.twig', [
            'colonization' => $colonization,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}")
     * @Method("GET")
     * @param Colonization $colonization
     * @return Response
     */
    public function showAction(Colonization $colonization)
    {
        $deleteForm = $this->createDeleteForm($colonization);

        return $this->render('DynamoColonizationBundle:Colonization:show.html.twig', [
            'colonization' => $colonization,
            'delete_form' => $deleteForm->createView(),
        ]);
    }

    /**
     * @Route("/{id}/zmen")
     * @Method({"GET", "PUT"})
     * @param Request $request
     * @param Colonization $colonization
     * @return Response
     * @Security("has_role('ROLE_USER')")
     */
    public function editAction(Request $request, Colonization $colonization)
    {
        $deleteForm = $this->createDeleteForm($colonization);
        $editForm = $this->createForm(ColonizationType::class, $colonization, ["method" => "PUT"]);
        $editForm->handleRequest($request);

        if ($editForm->isSubmitted() && $editForm->isValid()) {
            $this->getDoctrine()->getManager()->flush();
            $this->addFlash("success", $this->getTranslator()->trans("colonization.changed"));
            return $this->redirectToRoute('dynamo_colonization_colonization_index');
        }

        return $this->render('DynamoColonizationBundle:Colonization:edit.html.twig', [
            'colonization' => $colonization,
            'form' => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        ]);
    }

    /**
     * @param Request $request
     * @param Colonization $colonization
     * @Route("/{id}")
     * @Method("DELETE")
     * @return Response
     * @Security("has_role('ROLE_USER')")
     */
    public function deleteAction(Request $request, Colonization $colonization)
    {
        $form = $this->createDeleteForm($colonization);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($colonization);
            $em->flush();
            $this->addFlash('success', $this->getTranslator()->trans("colonization.deleted"));
        }

        return $this->redirectToRoute('dynamo_colonization_colonization_index');
    }

    /**
     * @param Colonization $colonization
     * @return Form
     */
    private function createDeleteForm(Colonization $colonization)
    {
        return $this->createFormBuilder()
            ->setAction($this->generateUrl('dynamo_colonization_colonization_delete', ['id' => $colonization->getId()]))
            ->setMethod('DELETE')
            ->getForm();
    }

    /**
     * @return TranslatorInterface
     */
    private function getTranslator()
    {
        return $this->get("translator");
    }
}

src/Dynamo/Bundle/ColonizationBundle/Resources/views/Colonization/edit.html.twig
{% extends 'DynamoColonizationBundle:Colonization:form.html.twig' %}

{% block action_name %}{{ 'colonization.edit'|trans }}{% endblock %}

{% block colonization_form %}
    <div class="form-group">
        <div class="pull-right">
            {{ form_start(delete_form) }}
            <input type="submit" value="{{ "delete"|trans }}" class="btn btn-danger btn-xs">
            {{ form_end(delete_form) }}
        </div>

        <label class="control-label required" for="colonization_id">Id</label>
        <input type="text" class="form-control" id="colonization_id" value="{{ colonization.id }}" disabled />
        {{ parent() }}
    </div>
{% endblock %}

{% block action_button %}
    <input type="submit" class="btn btn-default" value="{{ "edit"|trans }}" />
{% endblock %}

{% block latitude %}
    {% if colonization.correctMap %}
        {{ colonization.mapLat }}
    {% else %}
        {{ parent() }}
    {% endif %}
{% endblock %}

{% block longitude %}
    {% if colonization.correctMap %}
        {{ colonization.mapLng }}
    {% else %}
        {{ parent() }}
    {% endif %}
{% endblock %}

src/Dynamo/Bundle/ColonizationBundle/Resources/views/Colonization/form.html.twig
{% extends 'DynamoPortalBundle::layout.html.twig' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-offset-1 col-sm-10 col-md-offset-3 col-md-6">
                <h2>
                    <a href="{{ path('dynamo_colonization_colonization_index') }}" class="pull-right"
                       style="font-size: 14px;">
                        {{ 'list'|trans }}
                    </a>
                    {% block action_name %}{% endblock %}
                    {{ 'colonization.entity'|trans }}
                </h2>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-offset-1 col-sm-10 col-md-offset-3 col-md-6">
                {% block colonization_form %}
                    {{ form_start(form) }}
                    {{ form_row(form.place) }}
                    {{ form_row(form.map) }}
                    <div class="form-group thumbnail">
                        <div id="colonization-map-container" style="width: 100%; height: 400px;"></div>
                    </div>
                    {{ form_rest(form) }}
                    <div class="text-center">
                        {% block action_button %}{% endblock %}
                    </div>
                    {{ form_end(form) }}
                    <a href="{{ path('dynamo_colonization_colonization_index') }}" class="pull-right"
                       style="font-size: 14px;">
                        {{ 'list'|trans }}
                    </a>
                {% endblock %}
            </div>
        </div>
        <br />
    </div>
{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" type="text/css" media="screen"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/css/bootstrap-datepicker.min.css"/>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script type="text/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/js/bootstrap-datepicker.min.js">
    </script>
    <script type="text/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/locales/bootstrap-datepicker.{{ app.request.locale }}.min.js">
    </script>
    <script type="text/javascript"
            src='http://maps.google.com/maps/api/js?sensor=false&libraries=places&key={{ google_api_key }}'>
    </script>

    {% javascripts
    'bundles/dynamoportal/js/jquery.collection.js'
    'bundles/dynamoportal/js/locationpicker.jquery.js'
    %}
    <script type="text/javascript" src="{{ asset_url }}"></script>
    {% endjavascripts %}

    <script type="text/javascript">
        $('.colonization-photos').collection();
        $('#colonization-map-container').locationpicker({
            location: {
                latitude: {% block latitude %}48.142073{% endblock %},
                longitude: {% block longitude %} 17.100293{% endblock %}
            },
            addressFormat: 'natural_feature',
            radius: 0,
            mapTypeId: google.maps.MapTypeId.hybrid,
            enableAutocomplete: true,
            enableAutocompleteBlur: true,
            zoom: 8,
            onchanged: function (currentLocation, radius, isMarkerDropped) {
                $("#colonization_map").val(currentLocation.latitude + ", " + currentLocation.longitude);
            }
        });
    </script>
{% endblock %}

src/Dynamo/Bundle/ColonizationBundle/Resources/views/Colonization/index.html.twig
{% extends 'DynamoPortalBundle::layout.html.twig' %}

{% block content %}
<div class="container">
    {% if is_granted("ROLE_USER") %}
    <div class="row">
        <div class="col-sm-12">
            <a href="{{ path('dynamo_colonization_colonization_new') }}" class="pull-right">
                {{ "colonization.new"|trans|lower }} {{ "colonization.entity"|trans|lower }}
            </a>
        </div>
    </div>
    {% endif %}

    <div class="row">
        <div class="col-md-12">
            <div class="thumbnail" style="height: 500px;">
                <div id="map_canvas" style="width: 100%; height: 100%;"></div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12">
            {% for colonization in colonizations %}
                <div class="panel panel-default" id="colonization-{{ colonization.id }}">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            {% if is_granted("ROLE_USER") %}
                                <a href="{{ path("dynamo_colonization_colonization_edit", {"id": colonization.id}) }}"
                                   class="btn btn-info btn-xs">
                                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                                </a>
                            {% endif %}
                            {{ colonization.place }}
                            <span class="small pull-right">
                                {% if colonization.oneDay %}
                                    {{ colonization.dateFrom|date('Y-m-d') }}
                                {% else %}
                                    {{ "colonization.date_from"|trans|lower }} {{ colonization.dateFrom|date('Y-m-d') }}
                                    {{ "colonization.date_to"|trans|lower }} {{ colonization.dateTo|date('Y-m-d') }}
                                {% endif %}
                            </span>
                        </h4>
                    </div>
                    <div class="panel-body" id="colonization-detail-{{ colonization.id }}">
                        <a href="{{ path("dynamo_colonization_colonization_show", {"id" : colonization.id}) }}"
                           data-target="colonization-detail-{{ colonization.id }}">
                            <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
                            {{ "showMore"|trans }}
                        </a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="https://maps.googleapis.com/maps/api/js?key={{ google_api_key }}"></script>

    <script type="text/javascript">
        var locations = [
        {% spaceless %}
            {% for colonization in colonizations %}
                {% if colonization.mapLat and colonization.mapLng %}
                    [
                        "{{ colonization.place }}",
                        {{ colonization.mapLat }},
                        {{ colonization.mapLng }},
                        {{ colonization.id }}
                    ]
                    {{ loop.last ? "" : "," }}
                {% endif %}
            {% endfor %}
        {% endspaceless %}
        ];

        function initColonizationMapAll() {
            var map = new google.maps.Map(document.getElementById('map_canvas'), {
                zoom: 5,
                center: new google.maps.LatLng(48.142073, 17.100293),
                mapTypeId: google.maps.MapTypeId.ROADMAP
            });

            var marker, i;
            for (i = 0; i < locations.length; i++) {
                marker = new google.maps.Marker({
                    position: new google.maps.LatLng(locations[i][1], locations[i][2]),
                    map: map
                });

                google.maps.event.addListener(marker, 'click', (function(marker, i) {
                    return function() {
                        var $target = $('#colonization-' + locations[i][3]);
                        var $top = $target.offset().top;
                        $top = $top - 140;
                        $('html,body').animate({scrollTop:$top}, 500);
                        $target.find('.panel-body > a').click();
                    }
                })(marker, i));
            }
        }

        (function ($) {
            $(".panel-body a[data-target]").on('click', function (e) {
                e.preventDefault();
                var $this = $(this);
                var $target = $this.attr('data-target');
                var $href = $this.attr('href');
                $.get($href, function (data) {
                    $("#" + $target).html(data);
                });
            });

            initColonizationMapAll();
        })(jQuery);
    </script>
{% endblock %}

src/Dynamo/Bundle/ColonizationBundle/Resources/views/Colonization/new.html.twig
{% extends 'DynamoColonizationBundle:Colonization:form.html.twig' %}

{% block action_name %}{{ 'colonization.new'|trans }}{% endblock %}

{% block action_button %}
    <input type="submit" class="btn btn-default" value="{{ 'create'|trans }}" />
{% endblock %}

src/Dynamo/Bundle/ColonizationBundle/Resources/views/Colonization/show.html.twig
<p class="lead">{{ colonization.note }}</p>

<div class="row">
    {% if colonization.colonizers is not empty %}
    <div class="col-md-{{ colonization.map is not empty ? 4 : 12 }}">
        <h4>{{ "colonization.colonizers"|trans }}</h4>
        <ul>
            {% for user in colonization.colonizers %}
            <li>{{ user.firstName }} {{ user.lastName }}</li>
            {% endfor %}
        </ul>
    </div>
    {% endif %}

    {% if colonization.map is not empty %}
    <div class="col-md-{{ colonization.colonizers is not empty ? 8 : 12 }}">
        <h4>{{ "colonization.map"|trans }}</h4>
        <div class="thumbnail">
            <div id="colonization-map-{{ colonization.id }}" style="width: 100%; height: 400px;"></div>
        </div>
    </div>
        {% if colonization.mapLat and colonization.mapLng %}
        <script>
            function initColonizationMap{{ colonization.id }}() {
                var uluru = {lat: {{ colonization.mapLat }}, lng: {{ colonization.mapLng }}};
                var map = new google.maps.Map(document.getElementById('colonization-map-{{ colonization.id }}'), {
                    zoom: 12,
                    center: uluru
                });
                var marker = new google.maps.Marker({
                    position: uluru,
                    map: map
                });
            }
            initColonizationMap{{ colonization.id }}();
        </script>
        {% endif %}
    {% endif %}
</div>

{% if colonization.photos is not empty %}
<div>
    <h4>{{ "colonization.photos"|trans }}</h4>
    {% for photo in colonization.photos %}
        <div class="thumbnail">
            <img src="{{ asset(photo.dir ~ photo.fileName) }}" alt="{{ photo.title }}" title="{{ photo.title }}" />
        </div>
    {% endfor %}
</div>
{% endif %}